'use client';

import Link from 'next/link';
import Navbar from '@/components/Navbar';
import { useBranding } from '@/contexts/BrandingContext';

export default function TermsPage() {
  const { appName } = useBranding();
  const effectiveDate = 'May 31, 2026';

  return (
    <div className="min-h-screen bg-neutral">
      <Navbar />
      <main className="container mx-auto px-4 py-10">
        <div className="max-w-4xl mx-auto card space-y-8">
          <div className="border-b pb-6">
            <p className="text-sm font-semibold text-secondary uppercase tracking-wide">Terms & Conditions</p>
            <h1 className="text-3xl md:text-4xl font-extrabold text-primary mt-2">{appName}</h1>
            <p className="text-sm text-gray-500 mt-2">Effective date: {effectiveDate}</p>
          </div>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">1. Acceptance of terms</h2>
            <p>
              By accessing or using {appName}, you agree to these Terms & Conditions and the Privacy Policy. If you do not agree, do not create an account or use the platform.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">2. Purpose of the platform</h2>
            <p>
              {appName} is provided to help authorized students and administrators manage dues, payments, receipts, account access, reports, and official payment-related communication.
            </p>
            <p>
              The platform should not be used for fraud, impersonation, unauthorized access, harassment, unrelated marketing, or any activity that violates school, departmental, payment provider, SMS provider, or legal requirements.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">3. Eligibility and under-13 users</h2>
            <p>
              You should only use this platform if you are an authorized student, administrator, or approved user of the institution or department operating the system.
            </p>
            <p>
              Users under 13 years old must not create or operate an account unless the account is created or authorized by a parent, guardian, school, department, or authorized administrator. If you are under 13 and do not have such authorization, you must not register.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">4. Account responsibility</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You must provide accurate student, phone, email, programme, and academic year information.</li>
              <li>You are responsible for keeping your login details confidential.</li>
              <li>Temporary passwords sent by SMS should be changed after login.</li>
              <li>You must not share another user’s account or try to access data that does not belong to you.</li>
              <li>Administrators must use their access only for official dues management purposes.</li>
            </ul>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">5. Payments and receipts</h2>
            <p>
              Payment amounts, dues, balances, and receipts are managed based on records entered or approved by authorized administrators. Online payments may be processed by a third-party payment provider, and manual payments may require administrator review.
            </p>
            <p>
              A payment is only considered confirmed when it is marked as approved, completed, or verified in the system. Receipts generated by the platform are provided for record keeping and reconciliation.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">6. Manual payment proof</h2>
            <p>
              If manual payment is enabled, you may be required to upload payment proof. Uploaded proof must be genuine, accurate, and related to the payment being submitted. False or misleading payment proof may lead to rejection, account suspension, or further administrative action.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">7. SMS and email communication</h2>
            <p>
              The platform may send SMS or email messages for payment confirmation, receipts, reminders, account notices, and login resets. Delivery may depend on telecom networks, SMS providers, email providers, and the accuracy of the user’s contact details.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">8. Administrator access</h2>
            <p>
              Administrators, treasurers, financial secretaries, and other approved roles must protect student information, avoid unnecessary disclosure, and use exports, reports, and records only for official institutional or departmental purposes.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">9. Prohibited actions</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Using false student information or impersonating another person.</li>
              <li>Submitting fake or altered payment proof.</li>
              <li>Trying to bypass authentication, payment verification, role permissions, or audit controls.</li>
              <li>Interfering with platform availability or attempting unauthorized access to the server, database, or accounts.</li>
              <li>Using personal data from the platform for unrelated advertising, sale, harassment, or non-official purposes.</li>
            </ul>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">10. Availability and accuracy</h2>
            <p>
              The platform is provided to support dues management, but it may occasionally be unavailable due to maintenance, hosting issues, payment provider downtime, network problems, or updates. Administrators should review records regularly to ensure accuracy.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">11. Changes to terms</h2>
            <p>
              These Terms & Conditions may be updated when the platform changes, when institutional requirements change, or when legal and compliance needs require updates. Continued use after updates means you accept the revised terms.
            </p>
          </section>

          <section className="space-y-3 text-gray-700 leading-relaxed">
            <h2 className="text-xl font-bold text-primary">12. Contact</h2>
            <p>
              For questions about these terms, contact the institution, department, or administrator responsible for operating {appName}.
            </p>
          </section>

          <div className="pt-6 border-t flex flex-wrap gap-3">
            <Link href="/privacy" className="btn-outline">View Privacy Policy</Link>
            <Link href="/" className="btn-primary">Back to Home</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
