'use client';

import { useState } from 'react';
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import api from '@/lib/api';
import toast from 'react-hot-toast';
import { ReceiptIcon, CheckCircleIcon, ExclamationIcon } from '@/components/Icons';
import { useBranding } from '@/contexts/BrandingContext';

export default function VerifyReceiptPage() {
  const { appName } = useBranding();
  const [receiptNumber, setReceiptNumber] = useState('');
  const [loading, setLoading] = useState(false);
  const [receipt, setReceipt] = useState<any>(null);
  const [notFound, setNotFound] = useState(false);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    const cleanNumber = receiptNumber.trim();
    if (!cleanNumber) {
      toast.error('Enter a receipt number');
      return;
    }

    setLoading(true);
    setReceipt(null);
    setNotFound(false);
    try {
      const res = await api.get(`/receipts/number/${encodeURIComponent(cleanNumber)}`);
      if (res.data.success) {
        setReceipt(res.data.data);
        toast.success('Receipt verified');
      }
    } catch (error: any) {
      setNotFound(true);
      toast.error(error.response?.data?.message || 'Receipt not found');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-neutral">
      <Navbar />
      <main className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto space-y-6">
          <div className="card text-center p-8">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-primary/10 text-primary flex items-center justify-center">
              <span className="w-9 h-9"><ReceiptIcon /></span>
            </div>
            <h1 className="text-3xl font-extrabold text-primary">Verify Receipt</h1>
            <p className="text-gray-500 mt-2">Confirm whether a payment receipt was generated by {appName}.</p>

            <form onSubmit={handleVerify} className="mt-6 flex flex-col sm:flex-row gap-3">
              <input
                className="input-field flex-1"
                placeholder="Enter receipt number"
                value={receiptNumber}
                onChange={e => setReceiptNumber(e.target.value)}
              />
              <button type="submit" disabled={loading} className="btn-primary sm:w-40">
                {loading ? 'Checking...' : 'Verify'}
              </button>
            </form>
          </div>

          {notFound && (
            <div className="card border-l-4 border-red-500 bg-red-50 p-6">
              <div className="flex gap-3 items-start">
                <span className="w-6 h-6 text-red-600"><ExclamationIcon /></span>
                <div>
                  <h2 className="font-bold text-red-800">Receipt not found</h2>
                  <p className="text-sm text-red-700 mt-1">Check the receipt number and try again. A receipt that cannot be verified should be treated as unconfirmed until an administrator checks it.</p>
                </div>
              </div>
            </div>
          )}

          {receipt && (
            <div className="card border-l-4 border-green-500 bg-green-50 p-6">
              <div className="flex gap-3 items-start mb-5">
                <span className="w-7 h-7 text-green-700"><CheckCircleIcon /></span>
                <div>
                  <h2 className="text-xl font-bold text-green-900">Receipt Verified</h2>
                  <p className="text-sm text-green-700">This receipt exists in the system records.</p>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Info label="Receipt Number" value={receipt.receipt_number} />
                <Info label="Student" value={receipt.full_name || receipt.student_name || '—'} />
                <Info label="Index Number" value={receipt.student_id || '—'} />
                <Info label="Due" value={receipt.due_name || '—'} />
                <Info label="Amount Paid" value={`GHS ${Number(receipt.amount_paid || 0).toFixed(2)}`} />
                <Info label="Balance" value={`GHS ${Number(receipt.balance || 0).toFixed(2)}`} />
                <Info label="Total Amount" value={`GHS ${Number(receipt.total_amount || 0).toFixed(2)}`} />
                <Info label="Issued" value={receipt.issued_at ? new Date(receipt.issued_at).toLocaleString('en-GH') : '—'} />
              </div>
            </div>
          )}

          <div className="text-center text-sm text-gray-500">
            <Link href="/" className="text-primary hover:underline">Back to Home</Link>
          </div>
        </div>
      </main>
    </div>
  );
}

function Info({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-white/70 border border-green-100 rounded-xl p-3">
      <p className="text-xs font-bold uppercase tracking-wide text-gray-400 mb-1">{label}</p>
      <p className="text-sm font-semibold text-gray-800 break-words">{value}</p>
    </div>
  );
}
