require('dotenv').config();
const { pool } = require('./database');
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');

async function seed() {
  let connection;
  try {
    connection = await pool.getConnection();
    const hashedPassword = await bcrypt.hash('password123', 10);
    const adminHashedPassword = await bcrypt.hash('Admin123!', 10);
    
    // 1. Seed Academic Years & Programmes (Static)
    const academicYears = ['2023/2024', '2024/2025', '2025/2026'];
    for (const year of academicYears) {
      await connection.query(`INSERT IGNORE INTO academic_years (id, name, is_active) VALUES (?, ?, ?)`, [uuidv4(), year, year === '2024/2025']);
    }
    
    const programmes = [
      { name: 'Computer Science', code: 'CS' },
      { name: 'Information Technology', code: 'IT' },
      { name: 'Software Engineering', code: 'SE' }
    ];
    for (const prog of programmes) {
      await connection.query(`INSERT IGNORE INTO programmes (id, name, code, is_active) VALUES (?, ?, ?, ?)`, [uuidv4(), prog.name, prog.code, true]);
    }
    
    // 2. Seed Admin Users
    const roles = [
      { role: 'president', email: 'admin@example.com' },
      { role: 'treasurer', email: 'treasurer@example.com' },
      { role: 'financial_secretary', email: 'fsecretary@example.com' }
    ];
    
    let adminUserId = null;

    for (const admin of roles) {
      const adminId = uuidv4();
      if (admin.role === 'president') adminUserId = adminId;
      await connection.query(
        `INSERT INTO users (id, email, password_hash, role, is_active) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE role = role`,
        [adminId, admin.email, adminHashedPassword, admin.role, true]
      );
    }
    
    // Fetch the actual admin ID to use for 'created_by' fields if ON DUPLICATE KEY happened
    const [adminRows] = await connection.query(`SELECT id FROM users WHERE email = 'admin@example.com' LIMIT 1`);
    if (adminRows.length > 0) adminUserId = adminRows[0].id;
    
    // 3. Generate dynamic timestamp suffix for uniqueness
    const suffix = Date.now().toString().slice(-6);
    
    // 4. Seed Students
    const studentRecords = [];
    const levels = [100, 200, 300, 400];
    
    for (let i = 1; i <= 5; i++) {
      const studentId = uuidv4();
      const userId = uuidv4();
      const indexNum = `0409${suffix}${i}`;
      const email = `student${i}_${suffix}@example.com`;
      const level = levels[i % levels.length];
      const programme = programmes[i % programmes.length].name;
      
      // Insert User
      await connection.query(
        `INSERT INTO users (id, email, password_hash, role, student_id, is_active) VALUES (?, ?, ?, ?, ?, ?)`,
        [userId, email, hashedPassword, 'student', indexNum, true]
      );
      
      // Insert Student
      await connection.query(
        `INSERT INTO students (id, user_id, student_id, full_name, email, level, programme, academic_year, phone_number, is_active) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [studentId, userId, indexNum, `Dummy Student ${i}`, email, level, programme, '2024/2025', `024000${suffix.slice(-4)}`, true]
      );
      
      studentRecords.push({ id: studentId, level, programme });
    }
    
    // 5. Seed Dues
    const dues = [
      { id: uuidv4(), name: `Departmental Dues (${suffix})`, amount: 150.00, year: '2024/2025' },
      { id: uuidv4(), name: `SRC Dues (${suffix})`, amount: 50.00, year: '2024/2025' },
      { id: uuidv4(), name: `Association Dues (${suffix})`, amount: 80.00, year: '2024/2025' }
    ];
    
    for (const due of dues) {
      await connection.query(
        `INSERT INTO dues (id, name, amount, academic_year, deadline, description, is_active, created_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        [due.id, due.name, due.amount, due.year, new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), 'Sample dues generated by seed script', true, adminUserId]
      );
    }
    
    // 6. Assign Dues to Students
    const assignments = [];
    for (const student of studentRecords) {
      // Assign all 3 dues to each student
      for (const due of dues) {
        const assignmentId = uuidv4();
        await connection.query(
          `INSERT INTO due_assignments (id, due_id, student_id, level, programme, amount, status) VALUES (?, ?, ?, ?, ?, ?, ?)`,
          [assignmentId, due.id, student.id, student.level, student.programme, due.amount, 'unpaid']
        );
        assignments.push({ id: assignmentId, due_id: due.id, student_id: student.id, amount: due.amount });
      }
    }
    
    // 7. Create Payments & Receipts
    // Student 1: Paid Departmental Dues fully (online)
    const payment1Id = uuidv4();
    await connection.query(
      `INSERT INTO payments (id, student_id, due_id, amount, service_fee, payment_method, payment_type, status, paystack_reference) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [payment1Id, studentRecords[0].id, dues[0].id, dues[0].amount, 0, 'paystack', 'online', 'completed', `REF_SEED_${suffix}_1`]
    );
    await connection.query(
      `UPDATE due_assignments SET status = 'paid' WHERE student_id = ? AND due_id = ?`,
      [studentRecords[0].id, dues[0].id]
    );
    await connection.query(
      `INSERT INTO receipts (id, receipt_number, student_id, due_id, payment_id, amount_paid, balance, total_amount, issued_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [uuidv4(), `REC-${suffix}-1`, studentRecords[0].id, dues[0].id, payment1Id, dues[0].amount, 0, dues[0].amount, adminUserId]
    );
    
    // Student 2: Pending manual payment for SRC Dues
    const payment2Id = uuidv4();
    await connection.query(
      `INSERT INTO payments (id, student_id, due_id, amount, service_fee, payment_method, payment_type, status, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [payment2Id, studentRecords[1].id, dues[1].id, dues[1].amount, 0, 'mtn_momo', 'manual', 'pending', 'Paid via MoMo, waiting approval']
    );
    
    // Student 3: Rejected manual payment for Association Dues
    const payment3Id = uuidv4();
    await connection.query(
      `INSERT INTO payments (id, student_id, due_id, amount, service_fee, payment_method, payment_type, status, notes, rejected_reason, approved_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [payment3Id, studentRecords[2].id, dues[2].id, dues[2].amount, 0, 'bank_transfer', 'manual', 'rejected', 'Bank transfer', 'Proof image was blurry and unreadable', adminUserId]
    );
    
    console.log('Database seeding completed successfully!');
    console.log(`Generated ${studentRecords.length} new dummy students.`);
    console.log(`Student password is: password123`);
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  } finally {
    if (connection) connection.release();
  }
}

seed();